{
    "name": "Educational Center",
    "version": "1.0",
    "summary": "Management system for educational centers",
    "description": "Manage courses, teachers, students, groups, and payments for educational centers",
    "category": "Education",
    "author": "Your Name",
    "depends": ["base", "mail"],
    'data': [
            'security/security.xml',
            'security/ir.model.access.csv',
            'data/res_groups.xml',
            'views/course_views.xml',
            'views/teacher_views.xml',
            'views/student_views.xml',
            'views/group_views.xml',
            'views/payment_views.xml',
            'views/dashboard_views.xml',
            'reports/payment_report.xml',
            'wizards/bulk_payment_confirm_views.xml',
    ],
    "demo": [],
    "installable": True,
    "application": True,
    "auto_install": False,
}
